Synchronisation Informations fro imapsync
NethServer/nethserver-mail pull request #216
Opened 2020-10-06 18:19 UTC by stephdl

The PR displays some informations about the synchronisation (size, folder and messages remotely and locally)

This version implements a modal with rows

2020-10-07 10:16 UTC, gsanchietti requested changes
I think we need to focus on user request: during job run, the admin would like to see the status of the current synchronization.
While all the information is present, data are difficult to read.

As you can see, there is no easy way for the user to know which is the synchronization percentage. I can propose to display the data in table-like manner or at least add a progress bar somewhere in the dialog.

Let's show some love for the user! ;)

2020-10-07 10:16 UTC, gsanchietti commented on api/imapsync/count
> +#!/usr/bin/perl
Please call this helper from the `read` api

2020-10-07 14:39 UTC, stephdl commented
> As you can see, there is no easy way for the user to know which is the synchronization percentage. I can propose to display the data in table-like manner or at least add a progress bar somewhere in the dialog.

I thought about a progress bar like you can find elsewhere in the UI, but 100 000 emails to synchronize is not an important information, what is important too is the size 100 000 * 1KB (like for mailling list) of 100 000 * 10MB

So I think the progress bar is useless

2020-10-07 14:53 UTC, gsanchietti commented
> So I think the progress bar is useless

Maybe a progress bar is not good, but a percentage of the size (or messages) already synchronized it's an helpful info.

> Probably what we could miss is the folder information because I believe they are created at the first sync

I agree.

2020-10-08 14:42 UTC, stephdl commented on ui/public/i18n/language.json
> +        "CheckAccountDiff":"Check account differences",
done

2020-10-08 14:42 UTC, stephdl commented on ui/public/i18n/language.json
> +        "PleaseWait":"Please wait, it might take a while",
done

2020-10-08 14:50 UTC, stephdl commented
> Maybe a progress bar is not good, but a percentage of the size (or messages) already synchronized it's an helpful info.

A percentage, a gauge, a circular graphic  I think is a wrong way to display information to the sysadmin user. In some cases, the number of messages on the local server is greater than on the remote server.

- If you sync without deleting the local messages not in the remote server
- if you sync a remote account on an existing email account

With the cases above I met the point where I had a percentage > 100%, this will bring issues. Only the number and the total size of messages can bring important information and if something is wrong (Why I cannot the last X emails for example)

I suggest to go with the modal

2020-10-08 15:02 UTC, gsanchietti commented
Let's go with the modal without the percentage

2020-10-08 15:02 UTC, gsanchietti approved these changes

2020-10-08 15:19 UTC, stephdl commented
this is the modal we can see

![Screenshot (22)](https://user-images.githubusercontent.com/3164851/95478845-5b7d3080-098a-11eb-9134-5496cf46432c.png)

2020-10-08 15:28 UTC, merged