Encode password to utf8 and add double-quotes for count messages
NethServer/nethserver-mail pull request #221
Opened 2020-10-15 16:15 UTC by stephdl

2020-10-16 06:47 UTC, gsanchietti reviewed
The code seems good, but I'd prefer that the whole pipe written in utf8.
I saw this example: https://www.perlmonks.org/?node_id=1120759

I'm not sure it fits our need. @DavidePrincipi what do you think?

2020-10-16 08:04 UTC, DavidePrincipi requested changes
- Please fix the `open()` invocation
- I'd analyse (and fix?) the `readInput()` function, to ensure the returned data is already in UTF-8 and prevent future bugs like this one.

2020-10-16 13:34 UTC, stephdl commented on api/imapsync/read
> +        "--port1",$Port,$crypt,"--user1",$username,"--password1","'".$password."'",
I just propose what the imapsync developer asks with old perl library : https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Unix.txt

I would prefer something simple and workable rather complicated solution ;)

2020-10-16 13:56 UTC, DavidePrincipi commented on api/imapsync/read
> +        "--port1",$Port,$crypt,"--user1",$username,"--password1","'".$password."'",
I'm not debating the FAQ solution. The above code surely works too. I'm asking to change the way `open()` is called: if you use the `open HANDLE, MODE, LIST` form you do not need to escape shell metacharacters, as the Perl manual says.

As consequence, the above code can be simplified by removing the quotes.

Another point is the use of spaces or new lines to make the `@imapsync` initialization easier to read...

2020-10-16 15:51 UTC, stephdl commented on api/imapsync/read
>  require '/usr/libexec/nethserver/api/lib/helper_functions.pl';
done

2020-10-16 15:51 UTC, stephdl commented on api/imapsync/read
> +        "--port1",$Port,$crypt,"--user1",$username,"--password1","'".$password."'",
done

2020-10-16 15:51 UTC, stephdl commented on api/imapsync/read
>      my @imapsync =("imapsync","--host2","localhost","--port2","143","--tls2","--user2",
done

2020-10-16 16:07 UTC, DavidePrincipi commented on api/imapsync/read
>          "--exclude","'^Public Folders$|^Trash$|^Deleted Items$|^Public".$exclude."'",
:warning: `$|` is a special Perl variable https://perldoc.perl.org/perlvar#$%7C

Furthermore, as Bash is not invoked by open() any more, the single quotes should be removed

```suggestion
        "--exclude", q(^Public Folders$|^Trash$|^Deleted Items$|^Public) . $exclude,
```

2020-10-16 16:40 UTC, stephdl commented
I needed to remove the `$` in the list of folder name else the subfolders are not included in the exclusion list

2020-10-19 06:54 UTC, DavidePrincipi approved these changes

2020-10-20 06:55 UTC, merged